### ISSUE TITLE
Atom 1.4.90 breaks font loading (on Windows)

### ISSUE THREAD

**Issue by rocketinventor** [samuelivarsson/atom-iv-terminal#5]
In the last version of Atom (for Windows), the behavior was changed such that plugins and shell can load before Atom's preferences file loads. This results in some other strange font being loaded instead of the one that I set.

Desired behaviour:
![image](https://user-images.githubusercontent.com/6473114/88682714-a9102e00-d0fb-11ea-96f0-b972da46ecaf.png)

Buggy behaviour:
![image](https://user-images.githubusercontent.com/6473114/88682509-68b0b000-d0fb-11ea-946d-dfcb6d349cfa.png)

A possible fix might be to wait to load the terminal or to re-draw it once the preferences file is finished loading.

To clarify: This behavior only happens if the terminal was open _before_ window launch/relaunch (which is quite often).

Caused by: https://github.com/atom/atom/pull/20547

**Comment by rdnt** [comment]
Hi @rocketinventor , I am having a hard time reproducing this. I have set the option "Restore Previous Windows On Start" to "yes" on Atom's Core tab, the iv-terminal is set to "Match Theme" and has the default font (I reckon it is Consolas). My OS is Windows 10 64-bit.
Could you provide some instructions on how to reproduce this? Does this reproduce on a new install with just iv-terminal installed?

*Update:* Managed to reproduce this issue, just submitted a pull request that fixes it.
